# Generated by Django 4.1.5 on 2023-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/customer/'),
        ),
    ]
