# Generated by Django 4.1.5 on 2023-01-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_alter_customer_model_image'),
        ('products_app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer_model')),
            ],
        ),
    ]
