# Generated by Django 4.1.5 on 2023-01-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
