# Generated by Django 4.1.5 on 2023-01-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_remove_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
