# Generated by Django 4.1.5 on 2023-01-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_app', '0005_delete_cart'),
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prdct',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_app.product'),
        ),
    ]
