# Generated by Django 4.1.5 on 2023-01-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_delete_cart'),
        ('cart_app', '0006_remove_cart_date_remove_cart_is_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.product'),
        ),
    ]
