# Generated by Django 4.1.5 on 2023-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_alter_cart_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
